### ISSUE TITLE
Notify every client of a new user

### ISSUE THREAD

**Issue by ParkerD559** [ParkerD559/StudyGroup#18]
Somehow, every client in a group needs to be sent a message whenever someone new joins the group. The "new user message" could be something like: "NUSR [name]". Maybe create a Group PHP class that keeps track of every user and their respective socketstreams to make that possible?

**Comment by ParkerD559** [comment]
Do we know what to do yet :P

**Comment by juanmejia10** [comment]
Sorry I just got off work what did I miss? Only one trying to do what?

**Comment by GarretKelley** [comment]
so i was thinking. userinfo already has a status for online and offline, and we (will or should?) have a group table keeping track of users in a group. would a simple if statement that picks up when a user goes offline or when a new user comes into the group be enough to do it? if the person is offline, we remove them from group table, show them offline in client. if the person comes online, they will appear in the table, we can show them online. groups already have a radomly generated id in the group name, so we can match the changing status with the right group. then return group name to client along with person who's status changed. 'm a bit sick so idk if i worded that correctly. can talk more during our meeting

**Comment by fullernle** [comment]
@GarretKelley  That only works for one client though. I.E. 
User 1 Creates Group, Server Returns Group Name and User so UI can put it current User List.

User 2 Joins Group, right now all we return is list of user to the current client, so it would only be to User 2's client. User 2's client will show the list of users currently in the group as user 1 and user 2.  User 1 will still show user 1 as the only person in the group since we don't a function that writes to that specific socket when someone joins.

That being said, I think after yesterday's session we should be able to implement it easier now.  @ParkerD559 Just needs to update his Qt code so I can test it with the server/database.

**Comment by fullernle** [comment]
Resolved.
