### ISSUE TITLE
User left in group userList upon server/client crash

### ISSUE THREAD

**Issue by ParkerD559** [ParkerD559/StudyGroup#58]
Reproduction: Login, join group, stop server, restart server, login, join the same group, and there will now be two of you!!

Suggested fix:
1) An initialize function when the server starts that sets everyone in the userInfo table to Offline.
2) In the join group function, the userList is checked against the userInfo table to verify all in the userList is currently Online before sending the "update userlist" code to all the clients.

**Comment by fullernle** [comment]
So I did the first part. 
1. The server whenever started will now register every user as offline.
2. I believe I also did this, but it did not resolve the issue.  The userList is updated with only users that are online, but that isn't the problem.

The problem seems to be that whenever a crash happens, when the client logs back in, it has the old copy of the group.

**Comment by ParkerD559** [comment]
That's weird, because when the client is disconnected it deletes everything in the UI related to the group...

So, the server doesn't send 2 names but 2 names appear in the UI basically? Wait. Maybe it's inputting it twice into the userList column because technically you're online? Can you like do an insert only if there isn't one already or something?

**Comment by fullernle** [comment]
So what happens is that the name is already there.  It's already displayed even before the user rejoins.  I saw it before you fixed it.

**Comment by ParkerD559** [comment]
Yeah the bug was not deleting the group since it needed a success message back from a leave group message, which couldn't happen obviously because the server is disconnected lol. 

So, currently, we just need to figure out how to delete all users from all groups when the server is first started, right? Or a way to validate their online status or something.

**Comment by ParkerD559** [comment]
So basically I think we have to have a function that goes through all tables and deletes anything in the userList that isn't already NULL.

Anyone have an idea of how to do this in SQL? Maybe a SQL procedure?

**Comment by fullernle** [comment]
Yeah. I tried the online thing but that still bugs out if let's say 2 people crash in the same group, both relog, but both don't join the group. The first person who joins would still see the second person because it only checks for online. 

There's this simple function:
DELETE FROM $groupID
WHERE userList IS NOT NULL

Which just goes and deletes everyone in the group. The limitation is that it's only one table.  We need to find a way to iterate through all the tables when the server starts.. 

Something with this functionality..
Delete from all tables
Where column userList is not null.

**Comment by fullernle** [comment]
Issue Resolved.
